import type { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import MobileNav from "@/components/MobileNav";
import ClinicIcon from "@/components/ui/ClinicIcon";
import { clinic, faqs, treatments } from "@/config/clinic";

function Button({ href, children, variant = "primary", icon }: { href: string; children: ReactNode; variant?: "primary" | "secondary"; icon?: string }) {
  return <a className={`btn btn-${variant}`} href={href}>{icon && <ClinicIcon name={icon} size={18}/>}<span>{children}</span></a>;
}

export default function HomePage() {
  return (
    <main>
      <div className="topbar"><div className="container topbar-inner"><div className="topbar-left"><span><ClinicIcon name="clock" size={15}/>{clinic.hours}</span><i/><span><ClinicIcon name="pin" size={15}/>Mangalagiri, Andhra Pradesh</span></div><div className="socials"><span>Find Us:</span><a href={clinic.googleMapsUrl} target="_blank" rel="noreferrer" aria-label="Tanvi Dental Care on Google Maps"><ClinicIcon name="google" size={15}/></a>{clinic.social.instagram && <a href={clinic.social.instagram} target="_blank" rel="noreferrer" aria-label="Tanvi Dental Care on Instagram"><ClinicIcon name="instagram" size={15}/></a>}</div></div></div>

      <header className="site-header"><div className="container header-inner"><a href="#home" className="brand" aria-label="Tanvi Dental Care & Implant Centre"><Image src="/images/tanvi-logo-web.png" alt="Tanvi Dental Care & Implant Centre logo" width={64} height={64} priority/><span className="brand-copy"><strong>TANVI</strong><small>DENTAL CARE &amp;<br/>IMPLANT CENTRE</small></span></a><nav className="desktop-nav" aria-label="Primary navigation"><a className="active" href="#home">Home</a><a href="#about">About Us</a><a href="#doctors">Our Doctors</a><a href="#services">Treatments</a><a href="#guide">Patient Guide</a><a href="#faq">FAQs</a><a href="#contact">Contact Us</a></nav><div className="header-actions"><a className="header-phone" href={clinic.phoneHref}><ClinicIcon name="phone" size={19}/><span><strong>{clinic.phone}</strong><small>Call Us</small></span></a><a className="header-whatsapp" href={clinic.whatsappHref}><ClinicIcon name="whatsapp" size={19}/><span>WhatsApp Us</span></a></div><MobileNav /></div></header>

      <section className="hero" id="home" aria-labelledby="hero-title"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">Compassionate Care. Advanced Dentistry.</p><h1 id="hero-title">Healthy Smiles,<br/><em>Confident Lives.</em></h1><p className="hero-lead">Expert dental care in a comfortable environment.<br/>Your smile is our priority.</p><div className="hero-benefits"><div className="benefit"><span className="benefit-icon"><ClinicIcon name="tooth" size={22}/></span><div><strong>Advanced Technology</strong><small>Modern equipment for precise treatment</small></div></div><div className="benefit"><span className="benefit-icon"><ClinicIcon name="shield" size={22}/></span><div><strong>Safe &amp; Hygienic Care</strong><small>Strict sterilization &amp; hygiene protocols</small></div></div><div className="benefit"><span className="benefit-icon"><ClinicIcon name="users" size={22}/></span><div><strong>Patient First Approach</strong><small>Personalized care for every smile</small></div></div></div><div className="hero-actions"><Button href={clinic.phoneHref} icon="phone">Call Now: {clinic.phone}</Button><Button href={clinic.whatsappHref} variant="secondary" icon="whatsapp">Chat on WhatsApp</Button></div><p className="medical-note"><ClinicIcon name="info" size={13}/>Educational information — not a diagnosis. Treatment suitability is assessed by the dentist.</p></div></div><div className="hero-image-layer"><Image src="/images/tanvi-doctors-hero.jpg" alt="Dr. Naga Swathi Pokala and Dr. Prathap Naidu" width={1100} height={700} priority sizes="(max-width: 1080px) 100vw, 46vw"/></div></section>

      <section className="container quick-info" aria-label="Clinic information"><div><a className="info-link" href={clinic.googleMapsUrl} target="_blank" rel="noreferrer"><span className="info-icon"><ClinicIcon name="pin" size={34}/></span><span><strong>Location</strong><p>Mangalagiri, Andhra Pradesh<br/>Near Old Bus Stand</p></span></a></div><div><a className="info-link" href="#contact"><span className="info-icon"><ClinicIcon name="clock" size={34}/></span><span><strong>Hours</strong><p>{clinic.hours}<br/>Sunday: call to confirm/book</p></span></a></div><div><a className="info-link" href={clinic.phoneHref}><span className="info-icon"><ClinicIcon name="phone" size={34}/></span><span><strong>Call Us</strong><p>{clinic.phone}<br/>We’re here to help</p></span></a></div><div><a className="info-link" href={clinic.whatsappHref}><span className="info-icon whatsapp"><ClinicIcon name="whatsapp" size={34}/></span><span><strong>WhatsApp</strong><p>Appointments<br/>&amp; enquiries</p></span></a></div></section>

      <section className="services" id="services" aria-labelledby="services-title"><div className="container"><div className="section-heading"><p className="section-mark">✦</p><h2 id="services-title">Featured Dental Services</h2><p>Explore key treatment areas for you and your family</p></div><div className="service-grid">{treatments.slice(0,6).map((service)=><article className="service-item" key={service.name}><div className="service-icon"><ClinicIcon name={service.icon} size={30}/></div><h3>{service.name}</h3><p>{service.description}</p></article>)}</div><Link className="view-all" href="/treatments">View All Treatments <ClinicIcon name="arrow" size={17}/></Link></div></section>

      <section className="about-section" id="about"><div className="container about-inner"><div><p className="eyebrow">A calm, patient-first experience</p><h2>Professional care with a human approach.</h2></div><p>Tanvi Dental Care &amp; Implant Centre is presented around clear communication, comfortable care and personalised treatment planning. Every procedure should begin with an examination and an explanation of the options appropriate for your oral health.</p></div></section>

      <section className="doctors-section" id="doctors"><div className="container"><div className="doctors-heading section-heading"><p className="section-mark">✦</p><h2>Meet Our Doctors</h2><p>Specialist-led dental care</p></div><div className="doctor-grid"><article className="doctor-card doctor-card-photo"><div className="doctor-photo-wrap"><Image src="/images/doctors/naga-swathi.webp" alt="Dr. Naga Swathi Pokala" width={599} height={900} loading="lazy" sizes="(max-width: 680px) 100vw, (max-width: 820px) 680px, 40vw"/></div><div className="doctor-details"><h3>Dr. Naga Swathi Pokala</h3><p>BDS, MDS</p><strong>Oral &amp; Maxillofacial Surgeon</strong></div></article><article className="doctor-card doctor-card-photo"><div className="doctor-photo-wrap"><Image src="/images/doctors/prathap-naidu.webp" alt="Dr. Prathap Naidu" width={599} height={900} loading="lazy" sizes="(max-width: 680px) 100vw, (max-width: 820px) 680px, 40vw"/></div><div className="doctor-details"><h3>Dr. Prathap Naidu</h3><p>BDS, MDS</p><strong>Endodontist</strong></div></article></div><div className="section-actions"><Link className="view-all" href="/doctors">Meet the doctors <ClinicIcon name="arrow" size={17}/></Link></div></div></section>

      <section className="treatment-catalogue" id="treatment-catalogue"><div className="container"><div className="section-heading catalogue-heading"><p className="section-mark">✦</p><h2>Treatment Catalogue</h2><p>Explore the main treatment areas presented for patient guidance.</p></div><div className="catalogue-grid">{treatments.map((treatment)=><Link className="catalogue-card" href={`/treatments/${treatment.slug}`} key={treatment.name}><span className="catalogue-icon"><ClinicIcon name={treatment.icon} size={25}/></span><div><h3>{treatment.name}</h3><p>{treatment.description}</p></div></Link>)}</div><p className="catalogue-note"><ClinicIcon name="info" size={14}/>Treatment availability and suitability are confirmed after clinical assessment.</p></div></section>

      <section className="guide-section" id="guide"><div className="container guide-inner"><div><p className="eyebrow">Patient Guide</p><h2>Know what to expect before your visit.</h2><p className="guide-copy">Bring previous dental records or scans if available, share your current concerns clearly, and ask about treatment options, expected visits and after-care.</p></div><div className="journey"><span><b>01</b> Tell us your concern</span><span><b>02</b> Clinical examination</span><span><b>03</b> Treatment discussion</span><span><b>04</b> Personalised plan</span></div></div></section>

      <section className="reviews-section" id="reviews"><div className="container reviews-inner"><div><p className="eyebrow">Patient feedback</p><h2>Google rating snapshot.</h2><p>At the time this website data was updated, the Google Business listing showed a <strong>{clinic.googleRating.toFixed(1)}/5</strong> rating from <strong>{clinic.googleReviewCount} reviews</strong>. Ratings and review counts can change; the Google listing is the live source.</p><a className="review-link" href={clinic.googleMapsUrl} target="_blank" rel="noreferrer"><ClinicIcon name="google" size={18}/> View live Google profile <ClinicIcon name="arrow" size={16}/></a></div><div className="rating-card"><div className="rating-number">{clinic.googleRating.toFixed(1)}</div><div className="rating-stars" aria-label="5 out of 5 stars">★★★★★</div><p>{clinic.googleReviewCount} Google reviews</p><span>Snapshot · live listing may change</span></div></div></section>

      <section className="faq-section" id="faq"><div className="container faq-layout"><div className="faq-intro"><p className="eyebrow">Patient questions</p><h2>Frequently Asked Questions</h2><p>Clear answers for common appointment, location and treatment questions.</p><a className="btn btn-primary" href={clinic.whatsappHref}><ClinicIcon name="whatsapp" size={18}/> Ask on WhatsApp</a></div><div className="faq-list">{faqs.map((faq,index)=><details className="faq-item" key={faq.question} open={index===0}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></div></section>

      <section className="contact-section" id="contact"><div className="container contact-inner"><div><p className="eyebrow">Visit Tanvi Dental Care</p><h2>Find us near the Old Bus Stand.</h2><p>{clinic.address}</p><p className="sunday-note"><strong>Sunday bookings:</strong> call {clinic.phone} to confirm.</p><div className="contact-actions"><Button href={clinic.phoneHref} icon="phone">Call {clinic.phone}</Button><Button href={clinic.whatsappHref} variant="secondary" icon="whatsapp">WhatsApp</Button><a className="btn btn-secondary" href={clinic.googleMapsUrl} target="_blank" rel="noreferrer"><ClinicIcon name="pin" size={18}/>Open Google Maps</a></div></div><div className="map-card"><iframe title="Tanvi Dental Care & Implant Centre location on Google Maps" src="https://www.google.com/maps?q=Tanvi%20Dental%20Care%20%26%20Implant%20Centre%2C%20Mangalagiri%2C%20Andhra%20Pradesh&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /></div></div></section>

      <footer className="footer"><div className="container footer-inner"><div className="footer-brand"><Image src="/images/tanvi-logo-web.png" alt="Tanvi Dental Care logo" width={52} height={46}/><span><strong>TANVI</strong><small>DENTAL CARE &amp; IMPLANT CENTRE</small></span></div><p>{clinic.shortAddress} · {clinic.hours} · <a href={clinic.phoneHref}>{clinic.phone}</a></p><div className="footer-socials"><a className="footer-google" href={clinic.googleMapsUrl} target="_blank" rel="noreferrer"><ClinicIcon name="google" size={16}/> Google</a>{clinic.social.instagram && <a className="footer-google" href={clinic.social.instagram} target="_blank" rel="noreferrer"><ClinicIcon name="instagram" size={16}/> Instagram</a>}</div></div></footer>
      <div className="floating-actions"><a href={clinic.phoneHref} aria-label="Call Tanvi Dental Care"><ClinicIcon name="phone" size={23}/></a><a href={clinic.whatsappHref} aria-label="WhatsApp Tanvi Dental Care"><ClinicIcon name="whatsapp" size={23}/></a></div>
    </main>
  );
}
