import type { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import MobileNav from "@/components/MobileNav";
import ClinicIcon from "@/components/ui/ClinicIcon";
import DoctorCard from "@/components/doctors/DoctorCard";
import { clinic, faqs, treatments } from "@/config/clinic";
import { doctors } from "@/config/doctors";

function Button({ href, children, variant = "primary", icon }: { href: string; children: ReactNode; variant?: "primary" | "secondary"; icon?: string }) {
  return <a className={`btn btn-${variant}`} href={href}>{icon && <ClinicIcon name={icon} size={18}/>}<span>{children}</span></a>;
}

export default function HomePage() {
  return (
    <main>
      <div className="topbar"><div className="container topbar-inner"><div className="topbar-left"><span><ClinicIcon name="clock" size={15}/>{clinic.hours}</span><i/><span><ClinicIcon name="pin" size={15}/>Mangalagiri, Andhra Pradesh</span></div><div className="socials"><span>Find Us:</span><a href={clinic.googleMapsUrl} target="_blank" rel="noreferrer" aria-label="Tanvi Dental Care on Google Maps"><ClinicIcon name="google" size={15}/></a></div></div></div>

      <header className="site-header"><div className="container header-inner"><Link href="/" className="brand" aria-label="Tanvi Dental Care & Implant Centre"><Image src="/images/tanvi-logo-web.png" alt="Tanvi Dental Care & Implant Centre logo" width={64} height={64} priority/><span className="brand-copy"><strong>TANVI</strong><small>DENTAL CARE &amp;<br/>IMPLANT CENTRE</small></span></Link><nav className="desktop-nav" aria-label="Primary navigation"><Link className="active" href="/">Home</Link><Link href="/about">About Us</Link><Link href="/doctors">Our Doctors</Link><Link href="/services">Treatments</Link><Link href="#guide">Patient Guide</Link><Link href="/faq">FAQs</Link><Link href="/contact">Contact Us</Link></nav><div className="header-actions"><a className="header-phone" href={clinic.phoneHref}><ClinicIcon name="phone" size={19}/><span><strong>{clinic.phone}</strong><small>Call Us</small></span></a><a className="header-whatsapp" href={clinic.whatsappHref}><ClinicIcon name="whatsapp" size={19}/><span>WhatsApp Us</span></a></div><MobileNav /></div></header>

      <section className="hero" id="home" aria-labelledby="hero-title"><div className="container hero-inner"><div className="hero-copy"><p className="eyebrow">Specialist-led dental care</p><h1 id="hero-title">Healthy Smiles,<br/><em>Confident Lives.</em></h1><p className="hero-lead">Clear dental guidance and specialist care in a comfortable environment.</p><div className="hero-benefits"><div className="benefit"><span className="benefit-icon"><ClinicIcon name="tooth" size={22}/></span><div><strong>Specialist-led care</strong><small>Meet verified dental specialists at Tanvi.</small></div></div><div className="benefit"><span className="benefit-icon"><ClinicIcon name="shield" size={22}/></span><div><strong>Patient-first approach</strong><small>Clear explanations and thoughtful planning.</small></div></div><div className="benefit"><span className="benefit-icon"><ClinicIcon name="users" size={22}/></span><div><strong>Convenient contact</strong><small>Call or WhatsApp for enquiries.</small></div></div></div><div className="hero-actions"><Button href={clinic.phoneHref} icon="phone">Call Now: {clinic.phone}</Button><Button href={clinic.whatsappHref} variant="secondary" icon="whatsapp">Chat on WhatsApp</Button></div><p className="medical-note"><ClinicIcon name="info" size={13}/>Educational information — not a diagnosis. Treatment suitability is assessed by the dentist.</p></div></div><div className="hero-image-layer"><picture><Image src="/images/tanvi-doctors-hero.jpg" alt="Tanvi Dental Care doctors" width={1100} height={700} priority sizes="(max-width: 900px) 100vw, 54vw"/></picture></div></section>

      <section className="container quick-info" aria-label="Clinic information"><div><a className="info-link" href={clinic.googleMapsUrl} target="_blank" rel="noreferrer"><span className="info-icon"><ClinicIcon name="pin" size={34}/></span><span><strong>Location</strong><p>Mangalagiri, Andhra Pradesh<br/>Near Old Bus Stand</p></span></a></div><div><a className="info-link" href="#contact"><span className="info-icon"><ClinicIcon name="clock" size={34}/></span><span><strong>Hours</strong><p>{clinic.hours}<br/>Call to confirm availability</p></span></a></div><div><a className="info-link" href={clinic.phoneHref}><span className="info-icon"><ClinicIcon name="phone" size={34}/></span><span><strong>Call Us</strong><p>{clinic.phone}<br/>We’re here to help</p></span></a></div><div><a className="info-link" href={clinic.whatsappHref}><span className="info-icon whatsapp"><ClinicIcon name="whatsapp" size={34}/></span><span><strong>WhatsApp</strong><p>Appointments<br/>&amp; enquiries</p></span></a></div></section>

      <section className="services" id="services" aria-labelledby="services-title"><div className="container"><div className="section-heading"><p className="section-mark">✦</p><h2 id="services-title">Our Dental Services</h2><p>Dental treatment areas currently presented for patient guidance.</p></div><div className="service-grid">{treatments.slice(0,6).map((service)=><article className="service-item" key={service.name}><div className="service-icon"><ClinicIcon name={service.icon} size={30}/></div><h3>{service.name}</h3><p>{service.description}</p></article>)}</div><Link className="view-all" href="/services">View Treatment Guide <ClinicIcon name="arrow" size={17}/></Link></div></section>

      <section className="about-section" id="about"><div className="container about-inner"><div><p className="eyebrow">A calm, patient-first experience</p><h2>Professional care with a human approach.</h2></div><p>Tanvi Dental Care &amp; Implant Centre is presented around clear communication, comfortable care and personalized treatment planning. Every procedure should begin with an examination and an explanation of the options appropriate for your oral health.</p></div></section>

      <section className="doctors-section" id="doctors"><div className="container"><div className="doctors-heading section-heading"><p className="section-mark">✦</p><h2>Meet Our Doctors</h2><p>Specialist-led dental care</p></div><div className="doctor-grid">{doctors.map((doctor) => <DoctorCard key={doctor.slug} doctor={doctor} />)}</div></div></section>

      <section className="treatment-catalogue" id="treatment-catalogue"><div className="container"><div className="section-heading catalogue-heading"><p className="section-mark">✦</p><h2>Treatment Catalogue</h2><p>Explore the main treatment areas presented for patient guidance.</p></div><div className="catalogue-grid">{treatments.map((treatment)=><article className="catalogue-card" key={treatment.name}><span className="catalogue-icon"><ClinicIcon name={treatment.icon} size={25}/></span><div><h3>{treatment.name}</h3><p>{treatment.description}</p></div></article>)}</div><p className="catalogue-note"><ClinicIcon name="info" size={14}/>Treatment availability and suitability are confirmed after clinical assessment.</p></div></section>

      <section className="guide-section" id="guide"><div className="container guide-inner"><div><p className="eyebrow">Patient Guide</p><h2>Know what to expect before your visit.</h2><p className="guide-copy">Bring previous dental records or scans if available, share your current concerns clearly, and ask about treatment options, expected visits and after-care.</p></div><div className="journey"><span><b>01</b> Tell us your concern</span><span><b>02</b> Clinical examination</span><span><b>03</b> Treatment discussion</span><span><b>04</b> Personalised plan</span></div></div></section>

      <section className="reviews-section" id="reviews"><div className="container reviews-inner"><div><p className="eyebrow">Patient feedback</p><h2>See the live Google profile.</h2><p>The Google Business listing currently stored for this website data shows a <strong>{clinic.googleRating.toFixed(1)}/5</strong> rating from <strong>{clinic.googleReviewCount} reviews</strong>. The live Google listing may change.</p><a className="review-link" href={clinic.googleMapsUrl} target="_blank" rel="noreferrer"><ClinicIcon name="google" size={18}/> View Google profile <ClinicIcon name="arrow" size={16}/></a></div><div className="rating-card"><div className="rating-number">{clinic.googleRating.toFixed(1)}</div><div className="rating-stars" aria-label="5 out of 5 stars">★★★★★</div><p>{clinic.googleReviewCount} Google reviews</p><span>Live rating can change</span></div></div></section>

      <section className="faq-section" id="faq"><div className="container faq-layout"><div className="faq-intro"><p className="eyebrow">Patient questions</p><h2>Frequently Asked Questions</h2><p>Clear answers for common appointment, location and treatment questions.</p><Link className="btn btn-primary" href="/faq">View all FAQs</Link></div><div className="faq-list">{faqs.slice(0,5).map((faq,index)=><details className="faq-item" key={faq.question} open={index===0}><summary>{faq.question}<span>+</span></summary><p>{faq.answer}</p></details>)}</div></div></section>

      <section className="contact-section" id="contact"><div className="container contact-inner"><div><p className="eyebrow">Visit Tanvi Dental Care</p><h2>Find us near the Old Bus Stand.</h2><p>{clinic.address}</p><div className="contact-actions"><Button href={clinic.phoneHref} icon="phone">Call {clinic.phone}</Button><Button href={clinic.whatsappHref} variant="secondary" icon="whatsapp">WhatsApp</Button><a className="btn btn-secondary" href={clinic.googleMapsUrl} target="_blank" rel="noreferrer"><ClinicIcon name="pin" size={18}/>Open Google Maps</a></div></div><div className="map-card"><iframe title="Tanvi Dental Care & Implant Centre location on Google Maps" src="https://www.google.com/maps?q=Tanvi%20Dental%20Care%20%26%20Implant%20Centre%2C%20Mangalagiri%2C%20Andhra%20Pradesh&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /></div></div></section>

      <footer className="footer"><div className="container footer-inner"><div className="footer-brand"><Image src="/images/tanvi-logo-web.png" alt="Tanvi Dental Care logo" width={52} height={46}/><span><strong>TANVI</strong><small>DENTAL CARE &amp; IMPLANT CENTRE</small></span></div><p>{clinic.shortAddress} · {clinic.hours} · <a href={clinic.phoneHref}>{clinic.phone}</a></p><Link className="footer-google" href={clinic.googleMapsUrl} target="_blank"><ClinicIcon name="google" size={16}/> Google</Link></div></footer>
      <div className="floating-actions"><a href={clinic.phoneHref} aria-label="Call Tanvi Dental Care"><ClinicIcon name="phone" size={23}/></a><a href={clinic.whatsappHref} aria-label="WhatsApp Tanvi Dental Care"><ClinicIcon name="whatsapp" size={23}/></a></div>
    </main>
  );
}
